export const countries_list = [
  {name: 'Afghanistan', continent: 'asia'},
  {name: 'Albania', continent: 'europe'},
  {name: 'Algeria', continent: 'africa'},
  {name: 'American Samoa', continent: 'oceania'},
  {name: 'Andorra', continent: 'europe'},
  {name: 'Angola', continent: 'africa'},
  {name: 'Anguilla', continent: 'north_america'},
  {name: 'Antarctica', continent: 'antarctica'},
  {name: 'Antigua and Barbuda', continent: 'north_america'},
  {name: 'Argentina', continent: 'south_america'},
  {name: 'Armenia', continent: 'asia'},
  {name: 'Aruba', continent: 'north_america'},
  {name: 'Australia', continent: 'oceania'},
  {name: 'Austria', continent: 'europe'},
  {name: 'Azerbaijan', continent: 'europe'},
  {name: 'Bahamas', continent: 'north_america'},
  {name: 'Bahrain', continent: 'asia'},
  {name: 'Bangladesh', continent: 'asia'},
  {name: 'Barbados', continent: 'north_america'},
  {name: 'Belarus', continent: 'europe'},
  {name: 'Belgium', continent: 'europe'},
  {name: 'Belize', continent: 'north_america'},
  {name: 'Benin', continent: 'africa'},
  {name: 'Bermuda', continent: 'north_america'},
  {name: 'Bhutan', continent: 'asia'},
  {name: 'Bolivia', continent: 'south_america'},
  {name: 'Bosnia and Herzegovina', continent: 'europe'},
  {name: 'Botswana', continent: 'africa'},
  {name: 'Bouvet Island', continent: 'antarctica'},
  {name: 'Brazil', continent: 'south_america'},
  {name: 'British Indian Ocean Territory', continent: 'asia'},
  {name: 'British Virgin Islands', continent: 'north_america'},
  {name: 'Brunei', continent: 'asia'},
  {name: 'Bulgaria', continent: 'europe'},
  {name: 'Burkina Faso', continent: 'africa'},
  {name: 'Burundi', continent: 'africa'},
  {name: 'Cambodia', continent: 'asia'},
  {name: 'Cameroon', continent: 'africa'},
  {name: 'Canada', continent: 'north_america'},
  {name: 'Cape Verde', continent: 'africa'},
  {name: 'Caribbean Netherlands', continent: 'north_america'},
  {name: 'Cayman Islands', continent: 'north_america'},
  {name: 'Central African Republic', continent: 'africa'},
  {name: 'Chad', continent: 'africa'},
  {name: 'Chile', continent: 'south_america'},
  {name: 'China', continent: 'asia'},
  {name: 'Christmas Island', continent: 'asia'},
  {name: 'Cocos (Keeling) Islands', continent: 'asia'},
  {name: 'Colombia', continent: 'south_america'},
  {name: 'Comoros', continent: 'africa'},
  {name: 'Cook Islands', continent: 'oceania'},
  {name: 'Costa Rica', continent: 'north_america'},
  {name: 'Croatia', continent: 'europe'},
  {name: 'Cuba', continent: 'north_america'},
  {name: 'Curaçao', continent: 'north_america'},
  {name: 'Cyprus', continent: 'europe'},
  {name: 'Czechia', continent: 'europe'},
  {name: 'DR Congo', continent: 'africa'},
  {name: 'Denmark', continent: 'europe'},
  {name: 'Djibouti', continent: 'africa'},
  {name: 'Dominica', continent: 'north_america'},
  {name: 'Dominican Republic', continent: 'north_america'},
  {name: 'Ecuador', continent: 'south_america'},
  {name: 'Egypt', continent: 'africa'},
  {name: 'El Salvador', continent: 'north_america'},
  {name: 'Equatorial Guinea', continent: 'africa'},
  {name: 'Eritrea', continent: 'africa'},
  {name: 'Estonia', continent: 'europe'},
  {name: 'Eswatini', continent: 'africa'},
  {name: 'Ethiopia', continent: 'africa'},
  {name: 'Falkland Islands', continent: 'south_america'},
  {name: 'Faroe Islands', continent: 'europe'},
  {name: 'Fiji', continent: 'oceania'},
  {name: 'Finland', continent: 'europe'},
  {name: 'France', continent: 'europe'},
  {name: 'French Guiana', continent: 'south_america'},
  {name: 'French Polynesia', continent: 'oceania'},
  {name: 'French Southern and Antarctic Lands', continent: 'antarctica'},
  {name: 'Gabon', continent: 'africa'},
  {name: 'Gambia', continent: 'africa'},
  {name: 'Georgia', continent: 'asia'},
  {name: 'Germany', continent: 'europe'},
  {name: 'Ghana', continent: 'africa'},
  {name: 'Gibraltar', continent: 'europe'},
  {name: 'Greece', continent: 'europe'},
  {name: 'Greenland', continent: 'north_america'},
  {name: 'Grenada', continent: 'north_america'},
  {name: 'Guadeloupe', continent: 'north_america'},
  {name: 'Guam', continent: 'oceania'},
  {name: 'Guatemala', continent: 'north_america'},
  {name: 'Guernsey', continent: 'europe'},
  {name: 'Guinea', continent: 'africa'},
  {name: 'Guinea-Bissau', continent: 'africa'},
  {name: 'Guyana', continent: 'south_america'},
  {name: 'Haiti', continent: 'north_america'},
  {name: 'Heard Island and McDonald Islands', continent: 'antarctica'},
  {name: 'Honduras', continent: 'north_america'},
  {name: 'Hong Kong', continent: 'asia'},
  {name: 'Hungary', continent: 'europe'},
  {name: 'Iceland', continent: 'europe'},
  {name: 'India', continent: 'asia'},
  {name: 'Indonesia', continent: 'asia'},
  {name: 'Iran', continent: 'asia'},
  {name: 'Iraq', continent: 'asia'},
  {name: 'Ireland', continent: 'europe'},
  {name: 'Isle of Man', continent: 'europe'},
  {name: 'Israel', continent: 'asia'},
  {name: 'Italy', continent: 'europe'},
  {name: 'Ivory Coast', continent: 'africa'},
  {name: 'Jamaica', continent: 'north_america'},
  {name: 'Japan', continent: 'asia'},
  {name: 'Jersey', continent: 'europe'},
  {name: 'Jordan', continent: 'asia'},
  {name: 'Kazakhstan', continent: 'asia'},
  {name: 'Kenya', continent: 'africa'},
  {name: 'Kiribati', continent: 'oceania'},
  {name: 'Kosovo', continent: 'europe'},
  {name: 'Kuwait', continent: 'asia'},
  {name: 'Kyrgyzstan', continent: 'asia'},
  {name: 'Laos', continent: 'asia'},
  {name: 'Latvia', continent: 'europe'},
  {name: 'Lebanon', continent: 'asia'},
  {name: 'Lesotho', continent: 'africa'},
  {name: 'Liberia', continent: 'africa'},
  {name: 'Libya', continent: 'africa'},
  {name: 'Liechtenstein', continent: 'europe'},
  {name: 'Lithuania', continent: 'europe'},
  {name: 'Luxembourg', continent: 'europe'},
  {name: 'Macau', continent: 'asia'},
  {name: 'Madagascar', continent: 'africa'},
  {name: 'Malawi', continent: 'africa'},
  {name: 'Malaysia', continent: 'asia'},
  {name: 'Maldives', continent: 'asia'},
  {name: 'Mali', continent: 'africa'},
  {name: 'Malta', continent: 'europe'},
  {name: 'Marshall Islands', continent: 'oceania'},
  {name: 'Martinique', continent: 'north_america'},
  {name: 'Mauritania', continent: 'africa'},
  {name: 'Mauritius', continent: 'africa'},
  {name: 'Mayotte', continent: 'africa'},
  {name: 'Mexico', continent: 'north_america'},
  {name: 'Micronesia', continent: 'oceania'},
  {name: 'Moldova', continent: 'europe'},
  {name: 'Monaco', continent: 'europe'},
  {name: 'Mongolia', continent: 'asia'},
  {name: 'Montenegro', continent: 'europe'},
  {name: 'Montserrat', continent: 'north_america'},
  {name: 'Morocco', continent: 'africa'},
  {name: 'Mozambique', continent: 'africa'},
  {name: 'Myanmar', continent: 'asia'},
  {name: 'Namibia', continent: 'africa'},
  {name: 'Nauru', continent: 'oceania'},
  {name: 'Nepal', continent: 'asia'},
  {name: 'Netherlands', continent: 'europe'},
  {name: 'New Caledonia', continent: 'oceania'},
  {name: 'New Zealand', continent: 'oceania'},
  {name: 'Nicaragua', continent: 'north_america'},
  {name: 'Niger', continent: 'africa'},
  {name: 'Nigeria', continent: 'africa'},
  {name: 'Niue', continent: 'oceania'},
  {name: 'Norfolk Island', continent: 'oceania'},
  {name: 'North Korea', continent: 'asia'},
  {name: 'North Macedonia', continent: 'europe'},
  {name: 'Northern Mariana Islands', continent: 'oceania'},
  {name: 'Norway', continent: 'europe'},
  {name: 'Oman', continent: 'asia'},
  {name: 'Pakistan', continent: 'asia'},
  {name: 'Palau', continent: 'oceania'},
  {name: 'Palestine', continent: 'asia'},
  {name: 'Panama', continent: 'north_america'},
  {name: 'Papua New Guinea', continent: 'oceania'},
  {name: 'Paraguay', continent: 'south_america'},
  {name: 'Peru', continent: 'south_america'},
  {name: 'Philippines', continent: 'asia'},
  {name: 'Pitcairn Islands', continent: 'oceania'},
  {name: 'Poland', continent: 'europe'},
  {name: 'Portugal', continent: 'europe'},
  {name: 'Puerto Rico', continent: 'north_america'},
  {name: 'Qatar', continent: 'asia'},
  {name: 'Republic of the Congo', continent: 'africa'},
  {name: 'Romania', continent: 'europe'},
  {name: 'Russia', continent: 'europe'},
  {name: 'Rwanda', continent: 'africa'},
  {name: 'Réunion', continent: 'africa'},
  {name: 'Saint Barthélemy', continent: 'north_america'},
  {name: 'Saint Helena, Ascension and Tristan da Cunha', continent: 'africa'},
  {name: 'Saint Kitts and Nevis', continent: 'north_america'},
  {name: 'Saint Lucia', continent: 'north_america'},
  {name: 'Saint Martin', continent: 'north_america'},
  {name: 'Saint Pierre and Miquelon', continent: 'north_america'},
  {name: 'Saint Vincent and the Grenadines', continent: 'north_america'},
  {name: 'Samoa', continent: 'oceania'},
  {name: 'San Marino', continent: 'europe'},
  {name: 'Saudi Arabia', continent: 'asia'},
  {name: 'Senegal', continent: 'africa'},
  {name: 'Serbia', continent: 'europe'},
  {name: 'Seychelles', continent: 'africa'},
  {name: 'Sierra Leone', continent: 'africa'},
  {name: 'Singapore', continent: 'asia'},
  {name: 'Sint Maarten', continent: 'north_america'},
  {name: 'Slovakia', continent: 'europe'},
  {name: 'Slovenia', continent: 'europe'},
  {name: 'Solomon Islands', continent: 'oceania'},
  {name: 'Somalia', continent: 'africa'},
  {name: 'South Africa', continent: 'africa'},
  {name: 'South Georgia', continent: 'antarctica'},
  {name: 'South Korea', continent: 'asia'},
  {name: 'South Sudan', continent: 'africa'},
  {name: 'Spain', continent: 'europe'},
  {name: 'Sri Lanka', continent: 'asia'},
  {name: 'Sudan', continent: 'africa'},
  {name: 'Suriname', continent: 'south_america'},
  {name: 'Svalbard and Jan Mayen', continent: 'europe'},
  {name: 'Sweden', continent: 'europe'},
  {name: 'Switzerland', continent: 'europe'},
  {name: 'Syria', continent: 'asia'},
  {name: 'São Tomé and Príncipe', continent: 'africa'},
  {name: 'Taiwan', continent: 'asia'},
  {name: 'Tajikistan', continent: 'asia'},
  {name: 'Tanzania', continent: 'africa'},
  {name: 'Thailand', continent: 'asia'},
  {name: 'Timor-Leste', continent: 'oceania'},
  {name: 'Togo', continent: 'africa'},
  {name: 'Tokelau', continent: 'oceania'},
  {name: 'Tonga', continent: 'oceania'},
  {name: 'Trinidad and Tobago', continent: 'north_america'},
  {name: 'Tunisia', continent: 'africa'},
  {name: 'Turkey', continent: 'europe'},
  {name: 'Turkmenistan', continent: 'asia'},
  {name: 'Turks and Caicos Islands', continent: 'north_america'},
  {name: 'Tuvalu', continent: 'oceania'},
  {name: 'Uganda', continent: 'africa'},
  {name: 'Ukraine', continent: 'europe'},
  {name: 'United Arab Emirates', continent: 'asia'},
  {name: 'United Kingdom', continent: 'europe'},
  {name: 'United States', continent: 'north_america'},
  {name: 'United States Minor Outlying Islands', continent: 'oceania'},
  {name: 'United States Virgin Islands', continent: 'north_america'},
  {name: 'Uruguay', continent: 'south_america'},
  {name: 'Uzbekistan', continent: 'asia'},
  {name: 'Vanuatu', continent: 'oceania'},
  {name: 'Vatican City', continent: 'europe'},
  {name: 'Venezuela', continent: 'south_america'},
  {name: 'Vietnam', continent: 'asia'},
  {name: 'Wallis and Futuna', continent: 'oceania'},
  {name: 'Western Sahara', continent: 'africa'},
  {name: 'Yemen', continent: 'asia'},
  {name: 'Zambia', continent: 'africa'},
  {name: 'Zimbabwe', continent: 'africa'},
  {name: 'Åland Islands', continent: 'europe'}
]