name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install Root Dependencies
      run: npm ci

    - name: Install Client Dependencies
      run: cd client && npm ci

    - name: Install Server Dependencies
      run: cd server && npm ci

    - name: Run Backend Tests
      run: npm run test-server

    - name: Run Frontend Tests
      run: npm run test-client
